### ISSUE TITLE
Add Contributing Guide

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/autotelegram#28]
The [Readme.md](https://github.com/OSCA-Kampala-Chapter/autotelegram/blob/main/README.md) file has a [Getting Started](https://github.com/OSCA-Kampala-Chapter/autotelegram#getting-started) which more line with usage of autotelegram. Thus leaving a need for a contributing guide to guide newbies set up the development environment

**Comment by Samsonroyal** [comment]
Isn't a contributing guide not meant for individuals that want to push code to the project? I doubt those would be newbies.

**Comment by HassanBahati** [comment]
A`contributing guide` is meant for anyone who wants to contribute, whether day-one programmer, junior developer or senior developer. It acts as a walk through on how to set up development environment and get things running....so everyone who has not interfaced with that particular codebase is considered a newbie to it regardless of their programming experience.

So `newbie` in the perspective of **first time contributors** not in a level of experience perspective.

**Comment by Samsonroyal** [comment]
It makes sense now.

**Comment by HassanBahati** [comment]
> @HassanBahati I think this issue is done, right?

Yes it is
