### ISSUE TITLE
use url query string to get_updates

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autotelegram#5]
Telegram supports four ways of making requests to the bot API as shown [here](https://core.telegram.org/bots/api#making-requests).
Autobot uses application/json by default to make requests, but this seems to cause issues while passing parameters to the `get_updates` method.
specifically, `get_updates` has a parameter called `offset` which you pass in a value greater than the last update_id you received by one. So that means if the last update_id you received was 1000, offset will have to be 1001. This informs telegram that you've consumed the previous updates ad you need new one. If you don't send an offset, telegram will return updates that you might have already consumed.
The problem with the current json based request is that we cannot seem to encode the offset value right to be used by telegram. 
However, url encoding seems to work. 
So my suggestion is to switch from json based request to url encoding for `get_updates`

**Comment by kallyas** [comment]
How effective would this be compared to json parsing?

**Comment by ht-thomas** [comment]
I have not tested it out yet. But `get_updates` has simple parameters that wouldn't impose strain on parsing. since clearly json is not working, this seems like the most effective way.
